config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'pages/about'

  resources :welcomes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcomes#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/welcome.rb
class Welcome < ApplicationRecord
mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: 'Welcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params.require(:welcome).permit(:name, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheArtRoom Kampala</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Gugi" rel="stylesheet">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin|Montserrat" rel="stylesheet">
    <!-- Bootsrap -->
	 <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
	 <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="http://static1.squarespace.com/static/564e7a9fe4b06970c6919354/t/564e86a4e4b0172ec381e492/1524740018716/?format=1500w" style="max-width: 120px;"></a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Add Artpiece', new_welcome_path %></li>
        <li><a href="/pages/about">About Us</a></li>
        <li><a href="/welcomes/#explore">Explore</a></li>
      </ul>
    </div>
  </div>
</nav>
  
  
    
  		<%= yield %>


	<!--<footer>
  <div class="container">
    <img src="http://static1.squarespace.com/static/564e7a9fe4b06970c6919354/t/564e86a4e4b0172ec381e492/1524740018716/?format=1500w" style="max-width: 120px;"> <%= Time.now.year %>
    <p>Developed with <i class="fa fa-heart"></i> by <a href="http://samhez.com">Samuel Epodoi</a></p>
  </div>
	</footer>-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-text text-center container">
	<h1><b>Find that Art Piece <br>you didn’t even know you needed.</b></h1>
	<p>The Art Room Kampala was born because we know it can be difficult to describe your art taste, to describe the type of painting you are looking for. And where do you start your search? How to find that one, love at first sight, art piece? We thought about how to make this easier and came up with The Art Room, an algorithm based art recommendation engine. Don't search for art, we will recommend it based on your taste and preferences!
		<br> Developed with <i class="fa fa-heart"></i> by Samuel Epodoi</p>
</div>
<div class="img-about img-responsive" style="background-image: url('https://images.unsplash.com/photo-1511980725567-b9b7f0358905?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=da95e47c007f68868406d317f992fb32&auto=format&fit=crop&w=1297&q=80');"></div>

app/views/pages/img_hero.html.erb
<div style="background-image: url('https://images.pexels.com/photos/187334/pexels-photo-187334.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');" 
class="img-responsive img-hero text-center">
  <div class="overlay"></div>
    <div class="content-hero">
      <h1>The Art Room </h1>
      <p>Buy Beautiful Artpieces in Kampala by our awesome artists @paintnightkla</p>
      <a href="#explore"><button class="btn btn-primary">Explore Awesome Art  <i class="fa fa-paint-brush"></i></button></a>
    </div>
</div>

<!-- Image Links 
https://images.pexels.com/photos/542556/pexels-photo-542556.jpeg?auto=compress&cs=tinysrgb&h=350

https://images.unsplash.com/photo-1502744063339-1f16df671e12?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=50c15b1d9b5040437d1890609c60baff&auto=format&fit=crop&w=1061&q=80

https://images.pexels.com/photos/187334/pexels-photo-187334.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

https://images.pexels.com/photos/207665/pexels-photo-207665.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940


-->

app/views/welcomes/_form.html.erb
<div class="container.top-margin">
<%= form_with(model: welcome, local: true) do |form| %>
  <% if welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% welcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :welcome_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :welcome_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :welcome_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/welcomes/edit.html.erb
<div class="container top-margin">
<h1>Editing Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>
</div>

app/views/welcomes/index.html.erb
<p id="notice"><%= notice %></p>
<%=render template: "pages/img_hero" %>
<div class="container margin-bottom " id="explore">
<h1>Explore Art Pieces</h1>

<% @welcomes.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |welcome| %>
      <a href=""><div class="col-md-4">
      	<div class="img-artpiece">
	      <div class="image"> 
	      
	      	<%= link_to image_tag(welcome.picture_url, width: '100%'), welcome  if welcome.picture? %>	

	      		
	      </div>

		      <div class="artpiece-content">
			       <h4><%= link_to welcome.name, welcome %></h4>
			       <%= welcome.description %>
		       </div>

	    </div>

      </div></a>
    <% end %>
  </div>
<% end %>

<br>
</div>

app/views/welcomes/new.html.erb
<div class="container top-margin">
<h1>New Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Back', welcomes_path %>
</div>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show-details">
  <div class="container">
    <div class="row">
      <center><div class="col-md-7 arpiece-image ">
        <%= image_tag(@welcome.picture_url, height: 500) if @welcome.picture.present? %>
      </div></center>

      <div class="col-md-5 arpiece-details">
        <h3><%= @welcome.name %></h3>
        <hr>
        <p><%= @welcome.description %></p>
        <br>
        
        <p></p>

        <p>
          <%= link_to 'Edit', edit_welcome_path(@welcome) %> |
          <%= link_to 'Destroy', @welcome, data: { confirm: 'Are you sure?' }, method: :delete %> 
        </p>
        <h4>Size: 10cm<small>width</small> x 20cm<small>height</small></h4>
        <h4>Price: </h4>
        <br>
        <h5><i class="fa fa-home"></i> Get It Delivered to your doorstep</h5>
        <h5><i class="fa fa-lock"></i> Safe &amp; Secure</h5>
        <h5><i class="fa fa-money"></i> Pay On Delivery</h5>

        <button type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" class="btn btn-primary" style="margin-bottom: 15px;">Order Now<i class="fa fa-rocket"></i></button>

        <div class="collapse" id="collapseExample">
          <div class="card card-body">
              <div class="form-check">
                  <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2" data-toggle="modal" data-target="#exampleModalCenter" >
                  
                      <b>Pay Cash On Delivery</b>
                  
                </div>
                <div class="form-check disabled">
                  <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios3" value="option3" disabled>
                  
                    Pay Via Mobile Money
                 
                </div>
          </div>
        </div>

        

        
        <!-- Choose Delivery Location -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLongTitle">Please Choose A Delivery Point <i class="fa fa-map-pin"></i></h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>

              <form>
              <div class="modal-body">
                <div class="form-group">
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Enter the delivery Address here!"></textarea>
                  </div>
                <br>
                <h3 >Enter your details here</h3>
                <hr>
                <!-- User to input details -->
                
                      <input type="text" class="form-control" placeholder="Full Name">
                      <br>
                    <div class="form-group">
                      <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Telephone Number">
                    </div>

                    <div class="form-group">
                      
                      <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Email Address">
                      <small id="emailHelp" class="form-text text-muted">We'll use this to send you a recipt.</small>
                    </div>
                    
                </form>

              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal" data-toggle="modal" data-target="#exampleModalCenter2" >Make Your Order</button>
              </div>
            </div>
          </div>
        </div>


         <!-- Your Artpiece Is on the Way -->
        <div class="modal fade" id="exampleModalCenter2" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLongTitle">Your Artpiece Is on the way!</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body text-center">
                <img src="https://cdn.dribbble.com/users/803556/screenshots/3340807/dribbble-delivery.gif" style="max-height: 200px;">
                <h4>Your Artpiece will be delivered to you within 24hours! <br>Call us incase of anything(0712345678)</h4>
              </div>
              <div class="modal-footer">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times; Close</span>
                </button>
              </div>
            </div>
          </div>
        </div>





        <br>
        <h4><i class="fa fa-arrow-left"></i> <%= link_to 'Back', welcomes_path %></h4>
      </div>
    </div>
    
  </div>

</div>